chore: port over the existing docs
Incendo/cloud-docs pull request #9
Opened 2023-11-28 10:14 UTC by Citymonstret

2023-11-28 16:58 UTC, powercasgamer requested changes

2023-11-28 16:58 UTC, powercasgamer commented on docs/core/index.md
> +    final AggregateCommandParser<CommandSender, Location> locationParser = AggregateCommandParser<CommandSender>builder()
```suggestion
    final AggregateCommandParser<CommandSender, Location> locationParser = AggregateCommandParser.<CommandSender>builder()
```
missing a dot somewhere

2023-11-29 08:30 UTC, powercasgamer requested changes

2023-11-29 08:30 UTC, powercasgamer commented on docs/core/index.md
> +            final String input = input.peekString(); // Does not the remove the string!
```suggestion
            final String input = input.peekString(); // Does not remove the string from the input!
```
or similar

2023-11-29 14:53 UTC, Citymonstret commented
Note to self: add links to example-bukkit where relevant :)

2023-12-21 17:19 UTC, merged